---
# tasks file for nginx
- name: yum - Install and configure nginx
  block:
    - name: install nginx
      yum:
        name: nginx
        state: present
    - name: copy proxy.conf for reverse proxy
      template:
        src: proxy.conf
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        force: true
  become: true
  when: ansible_os_family == "RedHat"

- name: apt - Install and configure nginx
  block:
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: copy proxy.conf for reverse proxy
      template:
        src: proxy.conf
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        force: true
  become: true
  when: ansible_os_family == "Debian"

- name: enable and start nginx
  service:
    name: nginx
    enabled: true
    state: started
