---
- name: yum - Install nginx and configure it as a reverse proxy
  block:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: present
    - name: copy proxy.conf for reverse proxy
      ansible.builtin.template:
        src: proxy.conf
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        force: true
  when: ansible_os_family == "RedHat"

- name: apt - Install nginx and configure it as a reverse proxy
  block:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: copy proxy.conf for reverse proxy
      ansible.builtin.template:
        src: proxy.conf
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        force: true
  when: ansible_os_family == "Debian"

- name: enable and start nginx
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
