---
- name: yum - Install httpd
  block:
    - name: Install httpd and php
      ansible.builtin.yum:
        name:
          - httpd
          - php
          - php-mysql
          - php-common
        state: present
    - name: Set AllowOverride in httpd.conf for WordPress
      ansible.builtin.replace:
        path: /etc/httpd/conf/httpd.conf
        regexp: '(<[dD]irectory /var/www/>[^<]*)AllowOverride None'
        replace: '\1AllowOverride All'
  when: ansible_os_family == "RedHat"

- name: apt - Install apache2
  block:
    - name: Install apache2 and php
      ansible.builtin.apt:
        name:
          - apache2
          - php
          - php-mysql
          - php-common
        state: present
    - name: Set AllowOverride in apache2.conf for WordPress
      ansible.builtin.replace:
        path: /etc/apache2/apache2.conf
        regexp: '(<[dD]irectory /var/www/>[^<]*)AllowOverride None'
        replace: '\1AllowOverride All'
  when: ansible_os_family == "Debian"
