---
- name: yum - Install mariadb-server
  ansible.builtin.yum:
    name: mariadb-server
    state: present
  become: true
  when: ansible_os_family == "RedHat"
- name: apt - Install mariadb-server
  ansible.builtin.apt:
    name: mariadb-server
    state: present
  become: true
  when: ansible_os_family == "Debian"

- name: Start the MariaDB service
  ansible.builtin.service:
    name: mariadb
    state: started

- name: Create the WordPress database
  mysql_db:
    name: "{{ wordpress_db_name }}"
    state: present
    login_user: root
- name: Create the WordPress database user with grants
  mysql_user:
    name: "{{ wordpress_db_user }}"
    password: "{{ wordpress_db_user_pass }}"
    priv: "wordpress.*:ALL"
    login_user: root

# for extra security
- name: Disallow root login remotely # noqa no-changed-when
  ansible.builtin.command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
- name: Remove all anonymous user accounts
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent

# for extra security and to avoid easy root login for the test taker
- name: Randomize MariaDB root password
  mysql_user:
    name: root
    password: "{{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits,punctuation') }}"
    login_user: root
    login_password: ""
    check_implicit_admin: true
